### ISSUE TITLE
urbit-paper-collateral-renderer needs to be removed from npm

### ISSUE THREAD

**Issue by g-a-v-i-n** [urbit/PaperRenderer#149]
Now that the library name has changed, its probably best to remove this older one to avoid confusion.

https://www.npmjs.com/package/urbit-paper-collateral-renderer

**Comment by francescanarea** [comment]
@g-a-v-i-n npm doesn't let you remove a package completely but i did [deprecate](https://docs.npmjs.com/cli/deprecate) it

**Comment by francescanarea** [comment]
oh i could probably also make it private

**Comment by g-a-v-i-n** [comment]
Works for me, thank you!
